language: java
jdk: oraclejdk8

script:
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    -Dsonar.host.url=https://sonarcloud.io
    -Dsonar.organization=twiewiora-github
    -Dsonar.login=dba89d9bda7bbf2e2499e6378d4414bfd2164004

deploy:
  provider: heroku
  api_key: 50981cc6-59ef-407e-b4f1-b7a80bd847c4
  app:
    deployment: restaurant-booking-app

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
