language: java
jdk: oraclejdk8

before_install:
  - chmod +x runSonarQubeAnalysis.sh

script:
  - ./runSonarQubeAnalysis.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
